from django.urls import path

from .views import (
    admin_dashboard,
    admin_login,
    admin_logout,
    admin_reservations,
    admin_rooms,
    admin_inquiries,
    admin_room_create,
    admin_room_edit,
    admin_room_toggle_availability,
    admin_update_reservation,
    availability_search,
    booking_create,
    booking_list,
    contact_submit,
    checkout,
    customer_login,
    customer_logout,
    customer_register,
    customer_verify_otp,
    google_login,
    health_check,
    home,
    room_detail,
)

urlpatterns = [
    path('', home, name='home'),
    path('account/login/', customer_login, name='customer-login'),
    path('account/register/', customer_register, name='customer-register'),
    path('account/verify-otp/', customer_verify_otp, name='customer-verify-otp'),
    path('account/google/', google_login, name='google-login'),
    path('account/logout/', customer_logout, name='customer-logout'),
    path('rooms/<slug:slug>/', room_detail, name='room-detail'),
    path('admin/', admin_login, name='admin-login'),
    path('admin/dashboard/', admin_dashboard, name='admin-dashboard'),
    path('admin/reservations/', admin_reservations, name='admin-reservations'),
    path('admin/rooms/', admin_rooms, name='admin-rooms'),
    path('admin/rooms/new/', admin_room_create, name='admin-room-create'),
    path('admin/rooms/<int:room_id>/edit/', admin_room_edit, name='admin-room-edit'),
    path('admin/rooms/<int:room_id>/availability/', admin_room_toggle_availability, name='admin-room-toggle-availability'),
    path('admin/inquiries/', admin_inquiries, name='admin-inquiries'),
    path('admin/reservations/<int:reservation_id>/status/', admin_update_reservation, name='admin-update-reservation'),
    path('admin/logout/', admin_logout, name='admin-logout'),
    path('api/health/', health_check, name='health-check'),
    path('api/bookings/', booking_list, name='booking-list'),
    path('api/availability/', availability_search, name='availability-search'),
    path('api/bookings/create/', booking_create, name='booking-create'),
    path('contact/', contact_submit, name='contact-submit'),
    path('checkout/', checkout, name='checkout'),
]
