# Generated by Django 6.1.1 on 2026-09-09 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_otpchallenge_reservation_guest_user_guestprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(model_name='reservation', old_name='guest_user', new_name='customer_user'),
        migrations.RenameModel(old_name='GuestProfile', new_name='CustomerProfile'),
        migrations.AlterField(
            model_name='customerprofile',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='customer_profile',
                to='auth.user',
            ),
        ),
    ]
